#!/bin/bash
#10 numbrite välja printimine

summa=0
for ((i=10; i>0; i-- ))
do
        echo $i
        jaak=$(($i%2))
        if [ $jaak -eq 1 ]; then
        summa=$((summa+$i))
        fi

done
echo "paarisarvude summa on: $summa"
